name: dart_flutter_common
description: ZEN Messenger Dart and Flutter common.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  image_picker: ^1.0.2
  intl: 0.18.1
  photo_view: ^0.14.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
