name: flutter_tokyo_hackathon_2023
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  collection: ^1.17.2
  dart_flutter_common:
    path: ../dart_flutter_common
  firebase_auth: ^4.10.0
  firebase_common:
    path: ../firebase_common
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.1
  intl: ^0.18.1
  lottie: ^2.6.0

dev_dependencies:
  custom_lint: ^0.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  riverpod_lint: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
  
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Thin.ttf
          weight: 100

flutter_icons:
  android: true
  ios: true
