name: flutter_tokyo_hackathon_2023
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auto_route: ^7.7.0
  cloud_functions: ^4.3.4
  crypto: ^3.0.1
  dart_flutter_common:
    path: ../dart_flutter_common
  device_info_plus: ^9.0.3
  firebase_auth: ^4.7.2
  firebase_common:
    path: ../firebase_common
  firebase_core: ^2.15.0
  firebase_dynamic_links: ^5.3.4
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  flutter_line_sdk: ^2.3.3
  flutter_local_notifications: ^15.1.0+1
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  geoflutterfire_plus: ^0.0.14
  geolocator: ^9.0.2
  google_maps_flutter: ^2.4.0
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.7
  intl: ^0.18.1
  package_info_plus: ^4.1.0
  permission_handler: ^10.4.3
  rxdart: ^0.27.7
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^3.3.0

dev_dependencies:
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  mockito: ^5.4.2
  riverpod_lint: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
