name: flutter_tokyo_hackathon_2023
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  # cloud_functions: ^4.4.1
  dart_flutter_common:
    path: ../dart_flutter_common
  firebase_auth: ^4.10.0
  firebase_common:
    path: ../firebase_common
  firebase_core: ^2.16.0
  # firebase_dynamic_links: ^5.3.6
  # firebase_messaging: ^14.6.8
  # firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_image_compress: ^2.0.4
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.1
  intl: ^0.18.1
  sign_in_button: ^3.2.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  mockito: ^5.4.2
  riverpod_lint: ^1.4.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Thin.ttf
          weight: 100

flutter_icons:
  android: true
  ios: true
